### ISSUE TITLE
Where can I access this?

### ISSUE THREAD

**Issue by johanlindberg** [hackoutwest2016/MineOutWest#1]
This sounds awesome! How can I access this? Is there a server running somewhere?

**Comment by parbo** [comment]
No, we had problems getting a headless server up. But you can run it locally, by cloning the repo, following the readme on how to get the sound files, copy/symlink the final2 folder to run/saves,  running ./gradlew runClient, and opening the final2 save in single player mode.

**Comment by johanlindberg** [comment]
Ok. Will give it a try. Thanks.
